### ISSUE TITLE
can't pass "make test" 

### ISSUE THREAD

**Issue by kskhasegawa** [sikoba/isekai#11]
Hello
I'm interested in the library, but I can't pass "make test".
following message appears.

crystal spec
(enter) Call to r1cs_ppzksnark_generator   	[             ]	(1554782986.1363s x0.00 from start)
  (enter) Call to r1cs_constraint_system::swap_AB_if_beneficial	[             ]	(1554782986.1373s x0.00 from start)
    (enter) Estimate densities                 	[             ]	(1554782986.1382s x0.00 from start)
      * Non-zero A-count (estimate): 0
      * Non-zero B-count (estimate): 0
    (leave) Estimate densities                 	[0.0015s x0.05]	(1554782986.1397s x0.00 from start)
    Swap is not beneficial, not performing
  (leave) Call to r1cs_constraint_system::swap_AB_if_beneficial	[0.0033s x0.05]	(1554782986.1407s x0.00 from start)
  (enter) Call to r1cs_to_qap_instance_map_with_evaluation	[             ]	(1554782986.1412s x0.00 from start)
E    (enter) Parsing and Evaluating the circuit 	[             ]	(1554782986.1423s x0.00 from start)
Unable to open circuit file simple_example.arith 
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 255

What should I do?

**Comment by guipublic** [comment]
Hello,

The unit test is using some sample input files that were not commit. I have just added them so if you update the project the error should be gone now.

**Comment by kskhasegawa** [comment]
Thank you for the quick response!

By the way, is there any tutorial or some sample C file to generate .arith file?

**Comment by guipublic** [comment]
No we don't have more documentation. I plan to work on a tutorial to show how to prove and verify C programs with isekai but I won't have time this week.

You can generate with this command:
./isekai --arith=arith_file.arith my_sample.c
give the name you want for the circuit in the --arith option. my_sample.c is your input C program. Note that only a few features of C are supported and we already have known issues (with loops for instance) that we are working on.

**Comment by kskhasegawa** [comment]
OK, I'll try to create a C program that works the command correctly, and be waiting for your work :)
Thank you.

**Comment by guipublic** [comment]
The C program must have a specific signature (same as Pinocchio):
void outsource(struct Input * input, struct Output *)
You define input and output as needed (we only support int), and can add another struct as argumrnt for zero knowledge

**Comment by guipublic** [comment]
I am closing this issue because I have completed the usage section which should explain how to generate and verify proofs. Please note that most programs will fail because we do not support (yet) all features of C. For instance function calls and arrays are not supported (but is on the top of our list!).
